# Introduction to Numpy

Python lists:

* are very flexible
* don't require uniform numerical types
* are very easy to modify (inserting or appending objects).

However, flexibility often comes at the cost of performance, and lists are not the ideal object for numerical calculations.

This is where **Numpy** comes in. Numpy is a Python module that defines a powerful n-dimensional array object that uses C and Fortran code behind the scenes to provide high performance.

The downside of Numpy arrays is that they have a more rigid structure, and require a single numerical type (e.g. floating point values), but for a lot of scientific work, this is exactly what is needed.

The Numpy module is imported with:

In [1]:
import numpy

Although in the rest of this course, and in many packages, the following convention is used:

In [2]:
import numpy as np

This is because Numpy is so often used that it is shorter to type ``np`` than ``numpy``.

## Creating Numpy arrays

The easiest way to create an array is from a Python list, using the ``array`` function:

In [3]:
a = np.array([10, 20, 30, 40])

In [4]:
a

array([10, 20, 30, 40])

Numpy arrays have several attributes that give useful information about the array:

In [5]:
a.ndim  # number of dimensions

1

In [6]:
a.shape  # shape of the array

(4,)

In [7]:
a.dtype  # numerical type

dtype('int64')

*Note: Numpy arrays actually support more than just one integer type and one floating point type - they support signed and unsigned 8-, 16-, 32-, and 64-bit integers, and 16-, 32-, and 64-bit floating point values.*

There are several other ways to create arrays. For example, there is an ``arange`` function that can be used similarly to the built-in Python ``range`` function, with the exception that it can take floating-point input:

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 12, 2)

array([ 3,  5,  7,  9, 11])

In [10]:
np.arange(1.2, 4.4, 0.1)

array([1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3])

Another useful function is ``linspace``, which can be used to create linearly spaced values between and including limits:

In [11]:
np.linspace(11., 12., 11)

array([11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ])

and a similar function can be used to create logarithmically spaced values between and including limits:

In [12]:
np.logspace(1., 4., 7)

array([   10.      ,    31.622777,   100.      ,   316.227766,  1000.      ,  3162.27766 , 10000.      ])

Finally, the ``zeros`` and ``ones`` functions can be used to create arrays intially set to ``0`` and ``1`` respectively:

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## Exercise 1

Create an array which contains 11 values logarithmically spaced between $10^{-20}$ and $10^{-10}$.

In [15]:
# your solution here

Create an array which contains the value 2 repeated 10 times

In [16]:
# your solution here

Try using ``np.empty(10)`` and compare the results to ``np.zeros(10)`` - why do you think there is a difference?

In [17]:
# your solution here

Create an array containing 5 times the value 0, as a 32-bit floating point array (this is harder)

In [18]:
# your solution here

## Combining arrays

Numpy arrays can be combined numerically using the standard ``+-*/**`` operators:

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
x + 2 * y

array([ 9, 12, 15])

In [21]:
x ** y

array([  1,  32, 729])

Note that this differs from lists:

In [22]:
x = [1,2,3]
y = [4,5,6]

In [23]:
x + 2 * y

[1, 2, 3, 4, 5, 6, 4, 5, 6]

## Accessing and Slicing Arrays

Similarly to lists, items in arrays can be accessed individually:

In [24]:
x = np.array([9,8,7])

In [25]:
x[0]

9

In [26]:
x[1]

8

and arrays can also be **sliced** by specifiying the start and end of the slice (where the last element is exclusive):

In [27]:
y = np.arange(10)

In [28]:
y[0:5]

array([0, 1, 2, 3, 4])

optionally specifying a step:

In [29]:
y[0:10:2]

array([0, 2, 4, 6, 8])

As for lists, the start, end, and step are all optional, and default to ``0``, ``len(array)``, and ``1`` respectively:

In [30]:
y[:5]

array([0, 1, 2, 3, 4])

In [31]:
y[::2]

array([0, 2, 4, 6, 8])

## Exercise 2

Given an array ``x`` with 10 elements, find the array ``dx`` containing 9 values where ``dx[i] = x[i+1] - x[i]``. Do this without loops!

In [32]:
# your solution here

## Vectors

Vectors are simply one-dimensional arrays. Let's create another one via `linspace`:

In [33]:
z = np.linspace(2.3,8.6,10)
print("z=",z)

z= [2.3 3.  3.7 4.4 5.1 5.8 6.5 7.2 7.9 8.6]


there are special operations for vectors such as dot product

In [34]:
print("<z|z>=",np.vdot(z,z),"=",np.sum(z*z))
print("<z|z>=",np.vdot(z,y))
a = z + 1j * y # complex
print("a=",a)
print("<a|z>=",np.vdot(a,z),"=",np.sum(a.conj()*z))
print("<z|a>=",np.vdot(z,a))

<z|z>= 337.44999999999993 = 337.44999999999993
<z|z>= 303.0
a= [2.3+0.j 3. +1.j 3.7+2.j 4.4+3.j 5.1+4.j 5.8+5.j 6.5+6.j 7.2+7.j 7.9+8.j 8.6+9.j]
<a|z>= (337.44999999999993-303j) = (337.44999999999993-302.99999999999994j)
<z|a>= (337.44999999999993+303j)


## Multi-dimensional arrays

Numpy can be used for multi-dimensional arrays:

In [35]:
x = np.array([[1.,2.],[3.,4.]])

In [36]:
x.ndim

2

In [37]:
x.shape

(2, 2)

In [38]:
y = np.ones([3,2,3])  # ones takes the shape of the array, not the values

In [39]:
y

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
y.shape

(3, 2, 3)

Multi-dimensional arrays can be sliced differently along different dimensions:

In [41]:
z = np.ones([6,6,6])

In [42]:
z[::3, 1:4, :]

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

### Matrices

Matrices are two-dimensional arrays. Let's create three matrices, $\mathbf A$ with ones and $\mathbf B$ as diagonal  matrix,
and $\mathbf C$ as random *complex* matrix, next to a vector $\vec{x}$:

In [80]:
A = np.ones([3,3])
B = np.eye(3) # a diagonal matrix
C = np.random.rand(3,3) + 1j * np.random.rand(3,3) # add real and imaginary part
print("A=\n",A)
print("B=\n",B)
print("C=\n",C)
print("The transpose of C is\n",C.T)
print("The complex conjugate of C is\n",C.conj())
print("The hermitian of C is\n",C.T.conj())
print("the first column of C is \n",C[:,0])
print("the first row of C is \n",C[0,:])
print("The diagonal of B is\n",np.diag(B))
print("The the diagonal of C as diagonal matrix is \n",np.diag(np.diag(C)))


A=
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
C=
 [[0.195596+0.642293j 0.356263+0.949218j 0.411804+0.376788j]
 [0.361269+0.732548j 0.745339+0.878262j 0.938497+0.201401j]
 [0.570846+0.368404j 0.679574+0.328688j 0.166611+0.878163j]]
The transpose of C is
 [[0.195596+0.642293j 0.361269+0.732548j 0.570846+0.368404j]
 [0.356263+0.949218j 0.745339+0.878262j 0.679574+0.328688j]
 [0.411804+0.376788j 0.938497+0.201401j 0.166611+0.878163j]]
The complex conjugate of C is
 [[0.195596-0.642293j 0.356263-0.949218j 0.411804-0.376788j]
 [0.361269-0.732548j 0.745339-0.878262j 0.938497-0.201401j]
 [0.570846-0.368404j 0.679574-0.328688j 0.166611-0.878163j]]
The hermitian of C is
 [[0.195596-0.642293j 0.361269-0.732548j 0.570846-0.368404j]
 [0.356263-0.949218j 0.745339-0.878262j 0.679574-0.328688j]
 [0.411804-0.376788j 0.938497-0.201401j 0.166611-0.878163j]]
the first column of C is 
 [0.195596+0.642293j 0.361269+0.732548j 0.570846+0.368404j]
the first row of C is 
 [0.

In [82]:
print("The product of A times C is\n",A @ C)
print("The product of A times B times C' is\n",A @ B @ C.T.conj())

The product of A times C is
 [[1.127711+1.743244j 1.781176+2.156168j 1.516912+1.456352j]
 [1.127711+1.743244j 1.781176+2.156168j 1.516912+1.456352j]
 [1.127711+1.743244j 1.781176+2.156168j 1.516912+1.456352j]]
The product of A times B times C' is
 [[0.963663-1.9683j   2.045105-1.81221j  1.417031-1.575254j]
 [0.963663-1.9683j   2.045105-1.81221j  1.417031-1.575254j]
 [0.963663-1.9683j   2.045105-1.81221j  1.417031-1.575254j]]


In [83]:
x = np.array([1,2,3])
print("x * A=",x.T @ A)
print("<x|A|x>=",np.vdot(x,A@x))

x * A= [6. 6. 6.]
<x|A|x>= 36.0


## Exercise
Check `A @ C` by explicitly writing out loops

In [44]:
# your solution here

## [SKIP] Functions

In addition to an array class, Numpy contains a number of **vectorized** functions, which means functions that can act on all the elements of an array, typically much faster than could be achieved by looping over the array.

For example:

In [45]:
theta = np.linspace(0., 2. * np.pi, 10)

In [46]:
theta

array([0.      , 0.698132, 1.396263, 2.094395, 2.792527, 3.490659, 4.18879 , 4.886922, 5.585054, 6.283185])

In [47]:
np.sin(theta)

array([ 0.      ,  0.642788,  0.984808,  0.866025,  0.34202 , -0.34202 , -0.866025, -0.984808, -0.642788, -0.      ])

Another useful package is the ``np.random`` sub-package, which can be used to genenerate random numbers fast:

In [48]:
# uniform distribution between 0 and 1
np.random.random(10)

array([0.371688, 0.668365, 0.243857, 0.670224, 0.635523, 0.346303, 0.991886, 0.174645, 0.097365, 0.952965])

In [49]:
# 10 values from a gaussian distribution with mean 3 and sigma 1
np.random.normal(3., 1., 10)

array([3.040029, 3.282746, 0.504521, 2.877987, 3.4454  , 2.074472, 2.845839, 3.058177, 4.038718, 5.416589])

Another very useful function in Numpy is [numpy.loadtxt](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) which makes it easy to read in data from column-based data. For example, given the following file:

In [50]:
%cat data/columns.txt

1995.00274 0.944444
1995.00548 -1.61111
1995.00821 -3.55556
1995.01095 -9.83333
1995.01369 -10.2222
1995.01643 -9.5
1995.01916 -10.2222
1995.02190 -6.61111
1995.02464 -2.94444
1995.02738 1.55556
1995.03012 0.277778
1995.03285 -1.44444
1995.03559 -3.61111


We can either read it in using a single multi-dimensional array:

In [51]:
data = np.loadtxt('data/columns.txt')
data

array([[1995.00274 ,    0.944444],
       [1995.00548 ,   -1.61111 ],
       [1995.00821 ,   -3.55556 ],
       [1995.01095 ,   -9.83333 ],
       [1995.01369 ,  -10.2222  ],
       [1995.01643 ,   -9.5     ],
       [1995.01916 ,  -10.2222  ],
       [1995.0219  ,   -6.61111 ],
       [1995.02464 ,   -2.94444 ],
       [1995.02738 ,    1.55556 ],
       [1995.03012 ,    0.277778],
       [1995.03285 ,   -1.44444 ],
       [1995.03559 ,   -3.61111 ]])

Or we can read the individual columns:

In [52]:
date, temperature = np.loadtxt('data/columns.txt', unpack=True)

In [53]:
date

array([1995.00274, 1995.00548, 1995.00821, 1995.01095, 1995.01369, 1995.01643, 1995.01916, 1995.0219 , 1995.02464, 1995.02738, 1995.03012, 1995.03285, 1995.03559])

In [54]:
temperature

array([  0.944444,  -1.61111 ,  -3.55556 ,  -9.83333 , -10.2222  ,  -9.5     , -10.2222  ,  -6.61111 ,  -2.94444 ,   1.55556 ,   0.277778,  -1.44444 ,  -3.61111 ])

There are additional options to skip header rows, ignore comments, and read only certain columns. See the documentation for more details.

## [SKIP] Masking

The index notation ``[...]`` is not limited to single element indexing, or multiple element slicing, but one can also pass a discrete list/array of indices:

In [55]:
x = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])
x[[1,2,4,3,3,2]]

array([6, 4, 9, 7, 7, 4])

which is returning a new array composed of elements 1, 2, 4, etc from the original array.

Alternatively, one can also pass a boolean array of ``True/False`` values, called a **mask**, indicating which items to keep:

In [56]:
x[np.array([True, False, False, True, True, True, False, False, True, True, True, False, False, True])]

array([1, 7, 9, 3, 6, 7, 3, 3])

Now this doesn't look very useful because it is very verbose, but now consider that carrying out a comparison with the array will return such a boolean array:

In [57]:
x > 3.4

array([False,  True,  True,  True,  True, False, False,  True,  True,  True, False,  True,  True, False])

It is therefore possible to extract subsets from an array using the following simple notation:

In [58]:
x[x > 3.4]

array([6, 4, 7, 9, 5, 6, 7, 4, 4])

Conditions can be combined:

In [59]:
x[(x > 3.4) & (x < 5.5)]

array([4, 5, 4, 4])

Of course, the boolean **mask** can be derived from a different array to ``x`` as long as it is the right size:

In [60]:
x = np.linspace(-1., 1., 14)
y = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])

In [61]:
y[(x > -0.5) & (x < 0.4)]

array([9, 3, 1, 5, 6, 7])

Since the mask itself is an array, it can be stored in a variable and used as a mask for different arrays:

In [62]:
keep = (x > -0.5) & (x < 0.4)
x_new = x[keep]
y_new = y[keep]

In [63]:
x_new

array([-0.384615, -0.230769, -0.076923,  0.076923,  0.230769,  0.384615])

In [64]:
y_new

array([9, 3, 1, 5, 6, 7])

A mask can also appear on the left hand side of an assignment:

In [65]:
y[y > 5] = 0.

In [66]:
y

array([1, 0, 4, 0, 0, 3, 1, 5, 0, 0, 3, 4, 4, 3])

### [SKIP] NaN values

In arrays, some of the values are sometimes NaN - meaning *Not a Number*. If you multiply a NaN value by another value, you get NaN, and if there are any NaN values in a summation, the total result will be NaN. One way to get around this is to use ``np.nansum`` instead of ``np.sum`` in order to find the sum:

In [67]:
x = np.array([1,2,3,np.nan])

In [68]:
np.nansum(x)

6.0

In [69]:
np.nanmax(x)

3.0

You can also use ``np.isnan`` to tell you where values are NaN. For example, ``array[~np.isnan(array)]`` will return all the values that are not NaN (because ~ means 'not'):

In [70]:
np.isnan(x)

array([False, False, False,  True])

In [71]:
x[np.isnan(x)]

array([nan])

In [72]:
x[~np.isnan(x)]

array([1., 2., 3.])

## Exercise 3

The [data/munich_temperatures_average_with_bad_data.txt](data/munich_temperatures_average_with_bad_data.txt) data file gives the temperature in Munich every day for several years:

In [73]:
!head data/munich_temperatures_average_with_bad_data.txt  # shows the 10 first lines of a file

1995.00274 0.944444
1995.00548 -1.61111
1995.00821 -3.55556
1995.01095 -9.83333
1995.01369 -10.2222
1995.01643 -9.5
1995.01916 -10.2222
1995.02190 -6.61111
1995.02464 -2.94444
1995.02738 1.55556


Read in the file using ``np.loadtxt``. The data contains bad values, which you can identify by looking at the minimum and maximum values of the array. Use masking to get rid of the bad temperature values.

In [74]:

# your solution here


## Attentions with copying

Unlike python numbers, numpy arrays are not copied when being assigned. Note the following differences:

In [75]:
x = 1 # variable
y = 2
print("x,y=",x,y)
y = x
y = 4
print("x,y=",x,y)

x,y= 1 2
x,y= 1 4


In [76]:
x = np.ones(3) # numpy array
y = np.ones(3) + 3
print("x,y=",x,y)
y = x # OOPS! y is *assigned* to the x array. the previous y array is dropped!
y += 2
print("x,y=",x,y)

x,y= [1. 1. 1.] [4. 4. 4.]
x,y= [3. 3. 3.] [3. 3. 3.]


To avoid this, ony explicitly has to use the `copy` function:

In [77]:
x = np.ones(3) # numpy array
y = np.ones(3) + 3
print("x,y=",x,y)
y = x.copy() # COPY! alternative: np.copy(x)
y += 2
print("x,y=",x,y)

x,y= [1. 1. 1.] [4. 4. 4.]
x,y= [1. 1. 1.] [3. 3. 3.]
